# Default runtime profile for HHU HILBERT infrastructure / PBS Professional

cluster: >-
  qsub
  -A {cluster.account} -l walltime={cluster.run_hrs}:{cluster.run_min}:00
  -l select=1:ncpus={cluster.cores}:mem={cluster.mem_mb}mb
  -N {cluster.name} -o {cluster.output} -e {cluster.error}
cluster-config: profile/hilbert_cluster.json
local-cores: 1
jobs: 50
latency-wait: 300
keep-going: True
rerun-incomplete: True
restart-times: 0
max-status-checks-per-second: 0.001
use-conda: True
nolock: False
default-resources:
  - mem_per_cpu_mb=1024
  - mem_total_mb=1024
  - runtime_hrs=1
  - runtime_min=59
